spring:
  datasource:
    hikari:
      maximum-pool-size: 100
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/omf
      username: postgres
      password: vmfhgod11
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  redis:
    port: 6379